services:
  - type: web
    name: weathercraft-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: out
    branch: main

  - type: web
    name: weathercraft-backend
    env: python
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase: weathercraft-db
      - key: REDIS_URL
        value: redis://weathercraft-redis:6379/0

databases:
  - name: weathercraft-db
    databaseName: weathercraft
    user: weathercraft
    plan: standard

redis:
  - name: weathercraft-redis
    plan: starter
