version: "3.9"
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/workspace/frontend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    ports:
      - 3000:3000

  backend:
    build:
      context: ../services
      dockerfile: Dockerfile
    volumes:
      - ../services:/workspace/services
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: weathercraft
      POSTGRES_PASSWORD: weathercraft
      POSTGRES_DB: weathercraft
    ports:
      - 5432:5432

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
