name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: weathercraft
          POSTGRES_PASSWORD: weathercraft
          POSTGRES_DB: weathercraft
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U weathercraft" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/requirements.txt
      - name: Run Pytest
        run: pytest services

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:  
              node-version: '0'
              
      - name: Install dependencies
        working-directory: frontend
        run: npm install
      - name: Lint
        working-directory: frontend
        run: npm run lint
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          start: npm run dev
          wait-on: 'http://localhost:3000'
